services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: 'mysql:8.0'
    container_name: laravel_db_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  vite:
    image: node:16
    container_name: laravel-vite
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"

volumes:
  mysql_data:
