services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: laravel_app
    container_name: laravel_app_container
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  nginx:
    image: 'nginx:alpine'
    container_name: laravel_nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: 'mysql:8.0'
    container_name: laravel_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
